name: Gradle Publish CI

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@master
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
      env:
        gpg_private_key: ${{ secrets.gpg_private_key }}
        gpg_passphrase: ${{ secrets.gpg_passphrase }}
    - name: Publish with Gradle
      run: ./gradlew publish
      env:
        sonatype_username: ${{ secrets.sonatype_username }}
        sonatype_password: ${{ secrets.sonatype_password }}
